#cloud-config
users:
  - name: codeagent
    groups: users, admin, sudo
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    ssh_authorized_keys:
{{SSH_KEYS_PLACEHOLDER}}

vendor_data: {enabled: false}

package_update: false
package_upgrade: false

write_files:
  - path: /etc/systemd/system/opencode.service
    owner: root:root
    permissions: '0644'
    content: |
{{OPENCODE_SERVICE_FILE_PLACEHOLDER}}
  - path: /etc/opencode-server.env
    owner: root:root
    permissions: '0600'
    content: |
{{OPENCODE_ENV_FILE_PLACEHOLDER}}

runcmd:
  - |
{{OPENCODE_RUNCMD_PLACEHOLDER}}
